# Generated by Django 3.0.4 on 2020-03-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
