# Generated by Django 3.0.4 on 2020-03-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200311_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='recommendationType',
            field=models.CharField(default='jaccard', max_length=100),
            preserve_default=False,
        ),
    ]
