# Generated by Django 3.0.4 on 2020-03-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_recommendations_recommendationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='model',
            field=models.CharField(default='u', max_length=100),
            preserve_default=False,
        ),
    ]
